# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/web/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
